### ISSUE TITLE
csl.py 文件里的CSL数据集数据格式问题？

### ISSUE THREAD

**Issue by lonngxiang** [bojone/r-drop#2]
下载下来数据格式与代码里加载的不一致

**Comment by lonngxiang** [comment]
![image](https://user-images.githubusercontent.com/40717349/124689868-dff5e300-df0b-11eb-8cc9-c3e59865a0dd.png)

**Comment by bojone** [comment]
那就自行修改代码匹配。

**Comment by lonngxiang** [comment]
> 那就自行修改代码匹配。

好的，谢谢

**Comment by lonngxiang** [comment]
这好像一般电脑也跑不动
