### ISSUE TITLE
dropout rate 疑问

### ISSUE THREAD

**Issue by xuanzebi** [bojone/r-drop#7]
看了代码
bert里有两个dropout的rate，
attention_probs_dropout_prob，
hidden_dropout_prob，
所以调为0.3其实只修改了hidden_dropout_prob这个rate，transformer里attention模块的dropout rate（attention_probs_dropout_prob）还是0.1吧。

**Comment by bojone** [comment]
新版bert4keras修正了，两个dropout_rate都会调。
